spring.application.name=wallet

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Security Logging
logging.level.org.springframework.security=DEBUG

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000